### ISSUE TITLE
Verarbeitung anderer Audioformate

### ISSUE THREAD

**Issue by IngMiad** [BigDaddy-Germany/WHOAMI#105]
Da im Pflichtenheft von "allen gefundenen Musikdaten" die Rede ist, soll das Musikmodul neben MP3 noch weitere Audiodateien analysieren. Zurzeit wird lokal nur nach MP3 gefiltert.
Es wird zusätzlich die Anzahl aller gefundenen Musikdateien und ein Kommentar zu "Qualitätsbewussten" FLAC, ogg etc. Hörern implementiert.

**Comment by n2code** [comment]
Info dazu: FLAC ist lossless, also qualitätsbewusst!
Andere Formate würde ich nicht dazunehmen, denn OGGs und WAVs können bspw auch gut in Spielen enthalten sein, FLACs hingegen quasi nie :wink: 
Also falls du auch nach `.wav` und `.ogg` suchst, einfach nur die Anzahl ausgeben, aber ein sinnvolles Urteil ist da nicht möglich.
