### ISSUE TITLE
Messung Modullaufzeit

### ISSUE THREAD

**Issue by n2code** [BigDaddy-Germany/WHOAMI#108]
Irgendwas stimmt mit der Messung nicht, mit dem FileSearcher auf einem leeren Ordner und 60sek analyze time (Übergang nach 75%) geht er nach einer Sekunde nach Programmstart zu den Modulen über und meldet dann sofort....

```
Modul hat noch 4512 Millis
Modul hat noch 4512 Millis
Modul hat noch 4512 Millis
Modul hat noch 4509 Millis
Modul hat noch 4490 Millis
Modul hat noch 4490 Millis
```

Hatte in dem Zusammenhang auch schon einen ungerechtfertigten Instant-Abschuss meines Moduls

**Comment by mdoerfler** [comment]
Mit f9e76ec49a6e8c811820ee96b01c829a1c954ad3 behoben.
