### ISSUE TITLE
Kurskürzel im Bericht wieder in CAPS umwandeln

### ISSUE THREAD

**Issue by n2code** [BigDaddy-Germany/WHOAMI#111]

**Comment by marvinklose** [comment]
Ich schlage das GlobalData im Original vor, GlobalData macht dann alles klein und nur das erste Groß

**Comment by n2code** [comment]
@mdoerfler Capitalizing-Logik in global data schlauer machen?

**Comment by mdoerfler** [comment]
Das war damals so gedacht, dass der Vorgeschlagene Wert "Hans" mit "hans" übereinstimmt

Entweder ich nehme das wieder raus und nehme das, was an Groß-/Kleinschreibung als erstes vorgeschlagen wurde, oder ich mache eine Liste an den Worten, die Capslock geschrieben werden sollen.

Meinungen?

**Comment by n2code** [comment]
im Spielemodul steht sowas nach dem Motto
`if (original == toLower) then capitalize`

(vielleicht macht ja sogar der Ähnlichkeitsalgorithmus in dem Fall Sinn)

**Comment by mdoerfler** [comment]
Dazu fällt mir grade ein, dass das bei Mails blöd aussieht. Da wäre ne Liste schöner...

**Comment by n2code** [comment]
oder ein Parameter `boolean preserveCase` (der dann logischerweise auch ggf. bereits vorhandene Werte immer überschreibt) für die Vorschlagsmethode, dann können nämlich wieder die Module entscheiden und die Zuständigkeiten vermischen sich nicht

**Comment by mdoerfler** [comment]
oder es wird grundsätzlich groß-/kleinschreibung beachtet?

**Comment by marvinklose** [comment]
Einfachste Weg, es einfach beizubehalten oder?
