### ISSUE TITLE
Code Statistiken Too Much Input

### ISSUE THREAD

**Issue by marvinklose** [BigDaddy-Germany/WHOAMI#114]
- [x] Anaconda (Python Umgebung von Karl) "D:\Anaconda"
- [x] Javadoc "D:\Program Files\Java\javadocx"
- [x] Texlive "D:\texlive\2013\tlpkg\texworks\texworks-help\TeXworks-manual\en\index32.html"
- [x] git doc "D:\Program Files (x86)\SmartGitHg\git\doc\git\html\technical\api-diff.html"
- [x] ADT Bundle "D:\adt-bundle-windows-x86_64-20140702"
- [x] JavaFX "E:\Users\Marvin\Downloads\javafx_samples-2_2_72-windows\javafx-samples-2.2.72\src\DataApp\DataAppReadme.html"

Anaconda und JavaFx ebenfalls beim parsen nicht betrachten

**Comment by mdoerfler** [comment]
@marvinklose fixed?

**Comment by marvinklose** [comment]
Test startet nach dem ich Zuhause bin

**Comment by marvinklose** [comment]
Erfolgreich
