### ISSUE TITLE
Studienrichtung muss auch nur via Dropbox funktionieren

### ISSUE THREAD

**Issue by mdoerfler** [BigDaddy-Germany/WHOAMI#116]
Wenn kein Kurskalender aufgerufen wurde, muss die Studienrichtung trotzdem gefunden werden.

**Comment by mdoerfler** [comment]
Das Studienmodul findet meine Studienrichtung trotz Dropbox immer noch nicht.

**Comment by marvinklose** [comment]
Sollte für´s erste schon mal Ergebnisse liefern, aber unsere Dropbox könnte für TINF13AI[BI,BC;MF] haben gleich Wertung liefern

**Comment by marvinklose** [comment]
@mdoerfler Sollte jetzt besser laufen, testen dann Issue closen falls gesolved :+1:

**Comment by mdoerfler** [comment]
Auch im master? Da is nix neues

**Comment by marvinklose** [comment]
Mit 817ad61f563c67e13c915e92d51c1e60afd854ea gekommen

**Comment by mdoerfler** [comment]
Accepted
