### ISSUE TITLE
Art der Darstellung

### ISSUE THREAD

**Issue by marvinklose** [BigDaddy-Germany/WHOAMI#12]
Momentan sieht es wie folgt aus:
https://www.facebook.com/ 556 
http://www.schneckenhof.de/Home 296
https://www.facebook.com/marvk01 220 
https://www.youtube.com/feed/history 128 
https://www.youtube.com/my_history 121

Oder war der Plan nicht konkret nach einzelnen Links zu gehen, sondern nach der TopLevel-Domain aufzuhören?

**Comment by marvinklose** [comment]
HTML wie folgt:
<table
  <tr>
    <th>Webseite</th>
    <th>Aufrufe</th>
  </tr><tr><td>https://www.facebook.com/</td><td>556</td></tr><tr><td>http://www.schneckenhof.de/Home</td><td>296</td></tr><tr><td>https://www.facebook.com/marvk01</td><td>220</td></tr><tr><td>https://www.youtube.com/feed/history</td><td>128</td></tr><tr><td>https://www.youtube.com/my_history</td><td>121</td></tr></table>

**Comment by marvinklose** [comment]
Firefox gänge es relativ leicht nach .com oder so aufzuhören,
Chrome bietet dafür leider keine so schöne Spalte der Hosts an. :-1: 
Meinungen @n2code @IngMiad @mdoerfler

**Comment by mdoerfler** [comment]
Ich bin für Domains. Das ist aussagekräftiger

**Comment by IngMiad** [comment]
Domain find ich auch

**Comment by marvinklose** [comment]
<table> <tr> <th>Webseite</th> <th>Aufrufe</th> </tr><tr>  <td>www.facebook.com</td> <td>25985</td>  </tr><tr>  <td>www.schneckenhof.de</td> <td>17950</td>  </tr><tr>  <td>www.google.de</td> <td>4841</td>  </tr><tr>  <td>www.amazon.de</td> <td>2467</td>  </tr><tr>  <td>www.google.com</td> <td>1828</td>  </tr></table>
