### ISSUE TITLE
Demoberichte aus Testdaten generieren

### ISSUE THREAD

**Issue by n2code** [BigDaddy-Germany/WHOAMI#121]

**Comment by n2code** [comment]
@momoXD007 mention, weil man nur einen assignee zuweisen kann

**Comment by marvinklose** [comment]
@n2code Immer auf mich :sob:

**Comment by momoXD007** [comment]
also Kai-Frank und Holger sind fertig, die Frage jetzt ist wer der/die dritte PErson werden soll und wann wir das durchlaufen sollen, also sprich wie lange ihr noch Zeit haben wollt um was an euren Ausgaben zu verbessern

**Comment by marvinklose** [comment]
Ich halte feste:
Hoffi und Kai sind in der Dropbox
Das Ergebniss von meinem Laptop ist in der Dropbox
Michaels VM muss eventuell noch für die Präsentation getuned werden

**Comment by momoXD007** [comment]
Zur Sicherheit sollten wir dir die VM vielleicht auch noch überspielen...=
