### ISSUE TITLE
Musik Festplatten Aktivität

### ISSUE THREAD

**Issue by marvinklose** [BigDaddy-Germany/WHOAMI#122]
Musik liest wirklich jede MP3 komplett
siehe hier 
![unbenannt](https://cloud.githubusercontent.com/assets/7312459/4942639/b2d48370-65ed-11e4-809a-a5a1c6ee165f.PNG)

**Comment by marvinklose** [comment]
Information: Ich habe ca 31.00 Mp3-Datein ca 170 GB, bei mir läuft der Scan 12 Minuten, d.h. dem Modul verbleiben 18. bei 40mb/s max. Plattenleistung sind das sind etwa 2,5 GB pro Minute, also sind maximal etwas über 40GB bei mir möglich. Das ist etwas weniger als 1/4. :-1:

**Comment by IngMiad** [comment]
Okay. Könnte das eine Lösung sein?
![zeitvergabe](https://cloud.githubusercontent.com/assets/7457382/4956680/edcf536e-669d-11e4-9e21-f81afc870f75.png)

**Comment by IngMiad** [comment]
Hat jetzt ca. 16 Minuten Zeit

**Comment by IngMiad** [comment]
Und noch eine Performanceverbesserung: Ich trage jetzt alles direkt in einer Hashmap und überprüfe auf den Höchsten Wert. Dann kriegt man immer einen FavArtist und FavGenre raus (wenn mehr als 1 Audiodatei mit unfehlerhaften ID3-Tag installiert ist). Bis es halt abgebrochen wird...
