### ISSUE TITLE
GUI Testen

### ISSUE THREAD

**Issue by marvinklose** [BigDaddy-Germany/WHOAMI#123]
@mdoerfler @n2code @IngMiad @momoXD007 
Ihr könnte wie wild drauf lostesten, die meisten Möglichkeiten zu sabotieren sind hoffentlich abgeschaltet. 

Wenn ihr Module uns etwas mitteilen lassen wollte, dann nutzt folgendes 
<code>GuiManager.updateProgress("Lade und initialisiere Module...");</code>
oder 
<code>GuiManager.updateProgress("Man hast du viel Müll auf deiner Platte!");</code>
auch nett.

So happy testing :trollface:

**Comment by n2code** [comment]
Funktioniert ja eigentlich alles, bis auf...
@mdoerfler Stichwort synchronized?

**Comment by mdoerfler** [comment]
Was ist mit synchronized?

**Comment by n2code** [comment]
ist das mit dem "wenn ihr nicht aufpasst zerschießt es euch die ganze App" [Zitat P.S.] schon gelöst?

**Comment by mdoerfler** [comment]
Das müsste Marvin gelöst haben glaube ich
