### ISSUE TITLE
1. Zeile des Ladebildschirms

### ISSUE THREAD

**Issue by IngMiad** [BigDaddy-Germany/WHOAMI#127]
Also in unserem Szenario führt ein Student netterweise die Spionagesoftware aus und in der ersten Zeile wenn er das macht erschlägt ihn die Zeile "Lade und initialisiere Module...". Würde in mir ein Unsicherheitsgefühl auslösen. Wie wärs mit einem "WHOAMI - Was mein Computer über mich verrät. Viel Spaß ... blaaaa" oder so ähnlich?

**Comment by mdoerfler** [comment]
Guter Punkt, kannst du da was einbauen @marvinklose ?
