### ISSUE TITLE
Module melden CSV-Spalten an

### ISSUE THREAD

**Issue by n2code** [BigDaddy-Germany/WHOAMI#129]
- [x] Top5
- [x] Studien
- [x] Sport
- [x] PersonalData
- [x] Music
- [x] Food
- [x] Cdde
- [x] Syntax
- [x] Games

**Comment by n2code** [comment]
das Team auf mention setzten sobald Interface verfügbar

**Comment by mdoerfler** [comment]
Legt los @n2code @marvinklose @IngMiad @momoXD007 ;-)

**Comment by mdoerfler** [comment]
Sport, Studienrichtung und Top5? Sind die schon gemacht oder fehlen die noch? @marvinklose
