### ISSUE TITLE
Hilfsklasse für Helpermethoden

### ISSUE THREAD

**Issue by n2code** [BigDaddy-Germany/WHOAMI#13]
Sollen wir eine (effektiv statische) Hilfsklasse für Methoden anlegen, die für alle von Nutzen sein könnten?

**Comment by marvinklose** [comment]
Die was macht?

**Comment by n2code** [comment]
Komfortfunktionen die ich in mehr als nur meiner aktuellen Klasse brauchen könnte. Kleine Wrapper für Codeschnippsel.

**Comment by marvinklose** [comment]
Ja warum nicht, hab ja schon ne support Package angelegt :+1:

**Comment by n2code** [comment]
Klasse Utilities ist mit 3d8988f750129137ddf0b9d3ea91ee7bdcf3c043 geboren
