### ISSUE TITLE
Module erklären Scores in HTML

### ISSUE THREAD

**Issue by momoXD007** [BigDaddy-Germany/WHOAMI#130]
@momoXD007 @n2code @mdoerfler  @marvinklose @IngMiad  
Alle Module die Scores setzen sollten auch im HTML erklären dass sie das getan haben.
- [x] Top5
- [x] Studien
- [x] Sport
- [x] PersonalData
- [x] Music
- [x] Food
- [x] Cdde
- [x] Syntax
- [x] Games

**Comment by mdoerfler** [comment]
Auch hier Sport, Studien und top5? @marvinklose

**Comment by marvinklose** [comment]
Ja und damit closed :+1:
