### ISSUE TITLE
TOP 5 Ausgabe verbessern

### ISSUE THREAD

**Issue by momoXD007** [BigDaddy-Germany/WHOAMI#132]
- [x] Scores nutzen
- [x] Internetaktivitäten sollten kommentiert werden
- [ ] über die JSON könnte man eine Kommentierungsschnittstelle für alle möglichen URLs schaffen
- [x] ausgeben ob Chrome  oder FF mehr genutzt wird

**Comment by marvinklose** [comment]
Punkt 3 verworfen und in die Stringtemplates eingebaut
