### ISSUE TITLE
Spiele-Executables mit Liste abgleichen

### ISSUE THREAD

**Issue by n2code** [BigDaddy-Germany/WHOAMI#14]
- [x] JSON-Ressource erstellen (separates issue)
- [x] Spiele finden und hinzufügen
- [x] Timeboxing möglich machen

**Comment by momoXD007** [comment]
CoD2SP_s.exe -->COD2  (vermutlich SinglePlayer)-->Ego Shooter
iw3mp.exe        -->COD4 Multiplayer                        -->Ego Shooter
iw3sp.exe         -->COD4 SinglePlayer                     -->Ego Shooter
war3.exe          -->Warcraft III                                   -->Strategie/Action
Clonk.exe       --> Clonk Rage(hoher Nerdfaktor)     -->Aufbau/Strategie
(Quelle: mein Fundus)
COD4 ist allgemein auch als CODMW1 bekannt (heißt ausgeschrieben Call of Duty Modern Warfare 1)

**Comment by momoXD007** [comment]
codwaw.exe   -->COD5(World at War)-->Ego Shooter/Trash(wegen Zombie Mode)
...\The Witcher Enhanced Edition Director’s Cut\System\witcher.exe-->The Witcher Enhanced Edition--> Rollenspiel/Action
NFS.exe -->Need for Speed(welcher Teil hängt vom Ordner ab)-->Rennspiel

Quellen:(Internet vor Allem Steam-Forum)

**Comment by momoXD007** [comment]
Liste von Spielen die ich noch aufnehemen würde:
The Elder Scrolls(mindestens Morrorwind,Oblivion und Skyrim)
COD(die neuen Teile)
Far Cry (alle Teile)
Fallout(alle Teile)
GTA (alles ab Teil 3)
Assains Creed(alle Teile)
Fifa(die letzten 3)
Die Siedler
Anno
Civilization
CoH(Company of Heroes)-->Exe heißt aus'er Erinnerung raus glaube coh.exe
Silent Hunter (die letzten beiden)
Emergency
Die Sims(alle Teile)
Mass Effect
Stronghold
Roller Coaster 

und dann noch nen paar von diesen freakigen Simulationen wie "Kran Simulator" oder "Rotlicht Tycoon"

**Comment by marvinklose** [comment]
Geht das ganze jetzt eigentlich in eine JSON Datei?

**Comment by n2code** [comment]
höchstwahrscheinlich

PS: Ab sofort bitte Spieleideen in die Wiki :cat:

**Comment by n2code** [comment]
Funktionalität vollständig, Datenbasis siehe issue #61
