### ISSUE TITLE
Doch im Mülleimer gesucht?

### ISSUE THREAD

**Issue by marvinklose** [BigDaddy-Germany/WHOAMI#158]
Aktive Steam-Installation gefunden in E:\$RECYCLE.BIN\S-1-5-21-2427426453-2125608223-3402654696-1000\$RSBW7EA\Wir als Lieferant\Testdaten\Spiele\Steam\SteamApps

Könnte man aber auch als Feature interpretieren

**Comment by mdoerfler** [comment]
@marvinklose Bitte Bestätigung und Close, wenn der Fix erfolgreich war
