### ISSUE TITLE
USB-Stick abziehen bei laufendem Programm

### ISSUE THREAD

**Issue by mdoerfler** [BigDaddy-Germany/WHOAMI#164]
... ist so ziemlich das erste was dem Kruse einfallen wird und bringt unser Programm gegenwärtig meistens zum Abschmieren, weil er neue Klassen nicht mehr laden kann

Wenn wir es vor Ausführung auf den Rechner kopieren, fehlt uns der Pfad zur exe auf dem Stick, wo wir den Report speichern können

Eventuelle Lösung: Automatisierter Abbruch, sobald der Stick abgezogen wird? Geht das überhaupt?

Andere Lösungen?

@n2code @marvinklose @IngMiad @momoXD007

**Comment by momoXD007** [comment]
Vielleicht kann man das über den Class Loader abfangen, aber wissen tu ich das nicht.

**Comment by mdoerfler** [comment]
Phillip:

Per Reflection alle Klassen vorher anfassen, sodass sie geladen werden und auch sämtliche Ressourcen in den Speicher laden

--> Gerade mit den Ressourcen sehr ungünstig

**Comment by mdoerfler** [comment]
Andere Idee: Datei vorher in einen temporären Ordner kopieren:

Problem hier: Finden des ursprünglichen Pfades zum Speichern der Dateien (PDF, CSV)

**Comment by mdoerfler** [comment]
Wahrscheinlich umzusetzen: Temoräre Kopie der Datei anlegen.

**Comment by n2code** [comment]
gelöst mit 223b0e7920b12cd2384cc73ba73a63bd8bda463f :wine_glass:
