### ISSUE TITLE
Bugreport: Studiengang fehlt

### ISSUE THREAD

**Issue by n2code** [BigDaddy-Germany/WHOAMI#165]
Studiengang wird wohl verschluckt:

> In der CSV Datei steht angewandte informatik und im PDF wird das nicht gesagt, bzw. unterschlagen

**Comment by marvinklose** [comment]
Ist im Bericht sogar Fettgedruckt?!

**Comment by n2code** [comment]
Hab die Nachricht nur weitergegeben, vielleicht wurde das ja seit damals behoben
