### ISSUE TITLE
Kochmodul: Ordner filtern

### ISSUE THREAD

**Issue by n2code** [BigDaddy-Germany/WHOAMI#167]
Bitte File Separator in Filter integrieren, also irgendwie `**/*Kochen*/**.txt`
...denn folgendes darf nicht geschehen:
- Datei `backend.txt` wird gefunden
- Alles im Ordner `Backend` wird gematcht, im Sonderfall _Backen_ also am besten ganz strikt `**/Backen/**.txt`

**Comment by momoXD007** [comment]
nach Besprechung geclosed
