### ISSUE TITLE
Testdaten Musik mit UTF-16 Bug

### ISSUE THREAD

**Issue by IngMiad** [BigDaddy-Germany/WHOAMI#176]
@n2code @marvinklose @momoXD007 @mdoerfler 

Es wäre sehr hilfreich, wenn ihr eine Audiodatei habt, die diesen Bug hat zum testen.

**Comment by momoXD007** [comment]
Ich guck sofort

**Comment by momoXD007** [comment]
hab was in die Dropbox getan, seh bitte kurz nach ob dir die Datei hilft...

**Comment by IngMiad** [comment]
Ja perfekt, genau das Problem was ich gesucht habe
