### ISSUE TITLE
Veröffentlichung

### ISSUE THREAD

**Issue by n2code** [BigDaddy-Germany/WHOAMI#177]
im Team auf eine Lizenz einigen und mit dem Einverständnis aller das Projekt dann für die Öffentlichkeit freischalten

**Comment by n2code** [comment]
@marvinklose  @IngMiad  @momoXD007  @mdoerfler 
Irgendwelche Einwände gegen die MIT License?
https://tldrlegal.com/license/mit-license

**Comment by mdoerfler** [comment]
Nein passt mir so weit

**Comment by marvinklose** [comment]
Passt schon
