### ISSUE TITLE
Finden nativer Musikclients

### ISSUE THREAD

**Issue by IngMiad** [BigDaddy-Germany/WHOAMI#18]

**Comment by IngMiad** [comment]
Hier dasselbe: Wenn euch noch Alternativen zu ...
- Spotify
- iTunes
- Stream What You Hear
- simfy
  ...einfallen. Baue ich gerne noch ein!

**Comment by IngMiad** [comment]
@n2code, @marvinklose, @momoXD007, @mdoerfler

**Comment by momoXD007** [comment]
deezer

**Comment by momoXD007** [comment]
und weiß net ob es nicht auch noch was via amazon prime gibt...
