### ISSUE TITLE
Chefkoch URLs parsen

### ISSUE THREAD

**Issue by momoXD007** [BigDaddy-Germany/WHOAMI#22]
Chefkoch Strings parsen nach dem letzten Teil, sprich dem eigentlichen Gericht.

Vielleicht lässt sich der Hit-Count der im Browser ist auch noch sinnvoll integrieren. Fraglich ist hier nur wie man diesen Hit-Count gegenüber Rezepten auf der Festplatte vergleicht. Hier wäre ich offen für Vorschläge...

Beispiel Chefkoch URL:
http://www.chefkoch.de/rezepte/1108101216891426/Apfelkuchen-mit-Streuseln-vom-Blech.html

**Comment by momoXD007** [comment]
Das Parsing wurde mit dem oben referenzierten Commit eingefügt. Eine sinnvolle Bewertung oder sonstige Nutzung gibt es aber noch nicht.

**Comment by marvinklose** [comment]
Kannst ja die Visit_count Spalte mitnehmen

**Comment by momoXD007** [comment]
Wozu, genau?

**Comment by marvinklose** [comment]
Um aussagen über die Beliebtheit zu treffen

**Comment by momoXD007** [comment]
Ja gute Idee, aber wie willst du das mit Rezepten die lokal auf der Platte sind vergleichen?=

**Comment by momoXD007** [comment]
Lösung: das Ganze wird vollkommen getrennt betrachtet.
