### ISSUE TITLE
Musikmodul: ID3 Tags

### ISSUE THREAD

**Issue by mdoerfler** [BigDaddy-Germany/WHOAMI#23]
Im Architekturdokument stehen mehr Formate, als nur mp3. ID3 Tags gibt's aber nur dort. Wie verfahren wir mit anderen Dateien?

**Comment by marvinklose** [comment]
Ich meine das solche Tags in mehr Formaten als nur mp3 gibt.

**Comment by n2code** [comment]
@IngMiad Heute erfahren: `.flac` Dateien gibt es durchaus auch mit ID3-Tags, also einfach mal ebenfalls der library zum verarbeiten vorwerfen :+1:

**Comment by n2code** [comment]
und nochmal zur eigentlichen Frage: laut Pflichtenheft brauchen wir nur "Metainformationen von MP3-Dateien" und laut Architektur ID3-Tags

**Comment by IngMiad** [comment]
Okay ich lad mir morgen welche runter und werfe sie dem FileSearcher vor. Und zu Punkt zwei: Was genau ist der Unterschied? ID3Tag sind doch MetaInformation

**Comment by n2code** [comment]
ja klar, das meinte ich damit :smile: 
Wollte nur sagen, dass wir mit ID3 alles geforderte abdecken, weil das ja Metainfos sind^^
