### ISSUE TITLE
Browserverlauf nach Rezepten/Lieferservices durchsuchen

### ISSUE THREAD

**Issue by momoXD007** [BigDaddy-Germany/WHOAMI#3]
Ja die Browserverläufe müssen nach Rezeptseiten wie Chefkoch untersucht werden.
außerdem wird auch nach Seiten von Lieferservices und Pizzerien gesucht.

Task ist momentan blocked da die sqlite-Schnittstelle noch nicht verfügbar ist

**Comment by marvinklose** [comment]
Nach heute SQL Treiber im Master. Vielleicht schreib ich noch n Wiki Eintrag

**Comment by momoXD007** [comment]
Ist mit Commit 293143ebb7948a3378788e056e83d89d66882bb0 beta-mäßig implementiert.
