### ISSUE TITLE
API changes umsetzen

### ISSUE THREAD

**Issue by mdoerfler** [BigDaddy-Germany/WHOAMI#30]
Branch apichange muss gemerged werden. Dann die (eigenen) Module so anpassen, dass sie wieder laufen.
Bei Fragen an mich wenden - Auch bei Fragen, wie Files funktioniert (kompletter Ersatz für ein File Objekt in den meisten Fällen)

@n2code @IngMiad @marvinklose @momoXD007

**Comment by mdoerfler** [comment]
Hinweis: Bitte nur übergangsweise aus den Path Instanzen File Instanzen erstellen. Es sollte für unsere Anwendung möglich sein, immer nur die statischen Methoden von Files benutzen. 

Siehe auch http://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html

**Comment by momoXD007** [comment]
Marv und ich ham alles in unseren Modulen angepasst und in den API-Branch gemerged.

**Comment by mdoerfler** [comment]
Morgen gegen Ende der DB Vorlesung werde ich die Branch in den Master mergen.

**Comment by momoXD007** [comment]
Aja das Game-Module lief zumindest bei mir noch nicht. Also Niko muss noch was machen...=

**Comment by mdoerfler** [comment]
Alle Module, die bis dahin nicht laufen und sich schon im Master befinden, werde ich dann manuell auskommentieren, indem ich (temporär) "implements Analyzable" weg nehme. Dadurch wird das Modul nicht mehr eingebunden und es kann alles ausgeführt werden.
Außerdem ist das dann ja sogar irgendwie die Wahrheit, da es Analyzable dann nicht mehr wirklich implementiert.

**Comment by n2code** [comment]
Man sieht ja den Stress den API-Changes mit sich bringen (weshalb sie ja hoffentlich selten sind)... Weil man sich den Branch eben reinmerged und nicht nur die Änderungen bekommt. Die Profivariante wäre ein Cherry-Pick auf den FileSearcher und das Interface im `apichange` gewesen :laughing:

**Comment by n2code** [comment]
ebenfalls angepasst :+1: 
@IngMiad du fehlst noch, falls dich das noch gar nicht betrifft -> close :wink:

**Comment by n2code** [comment]
@mdoerfler Meldest du sobald der apichange wieder im master ist? beziehungsweise sollen wir bei zu veröffentlichenden Änderungen schon wieder direkt in den master pushen?

**Comment by mdoerfler** [comment]
apichange ist komplett im master
Branch apichange wurde vom Server gelöscht.

@momoXD007 @marvinklose @IngMiad @n2code ab jetzt wieder alles, was stable ist in den master mergen.

Bzw dran denken: ERST den master in die branch mergen und testen. DANACH die branch in den master mergen ;-)
