### ISSUE TITLE
Lieferung durch FileSearcher: Garantie auf Dateien?

### ISSUE THREAD

**Issue by n2code** [BigDaddy-Germany/WHOAMI#33]
Kann ich die definitive (vielleicht sogar in der Wiki verankerte) Garantie haben, dass der FileSearcher nur Dateien liefert? Um mir Checks auf `isFile()` oder so zu sparen?

**Comment by mdoerfler** [comment]
Der FileSearcher ist so ausgerichtet, dass er nur Dateien abliefert. Nimm diesem Comment als Garantie, welche Codingfehler nicht mit einschließt.

**Comment by n2code** [comment]
Gracias!
