### ISSUE TITLE
Module melden Einschränkungen wegen Timeboxing

### ISSUE THREAD

**Issue by n2code** [BigDaddy-Germany/WHOAMI#35]
Es wäre schön wenn auf welchen Protokollwegen auch immer die Module klar sagen könnten "Ich habe an der ein oder anderen Stelle abgebrochen, weil die Zeit um war"

Irgendwelche Vorschläge, wie?
Einfach nur etwas in den Log schreiben ist mir nicht standardisiert genug :stuck_out_tongue_winking_eye: 

@marvinklose @mdoerfler @momoXD007 @IngMiad

**Comment by mdoerfler** [comment]
Und was genau soll das bringen?

**Comment by n2code** [comment]
Eine informative Aussage. Bin schon öfters drüber gestolpert, dass ich mir nicht sicher war ob mein Modul nichts gefunden hat, oder ob es aufgrund zu geringer Zeit nicht weit genug gekommen ist. Die Scanergebnisse sind ja eigentlich reproduzierbar - außer Timeboxing schlägt eben zu.

**Comment by marvinklose** [comment]
Einfach ein Stern hinter dem Ergebnis
- alle Angaben ohne Gewähr

**Comment by n2code** [comment]
ist vorerst geklärt
