### ISSUE TITLE
Eigenes Paket für Spielemodul

### ISSUE THREAD

**Issue by n2code** [BigDaddy-Germany/WHOAMI#36]
Langsam wirds zu unübersichtlich, es spricht alles dafür das in ein eigenes Paket mit vielen schönen Klassen zu packen :sweat_smile:

**Comment by marvinklose** [comment]
Es gibt ein Support package

**Comment by n2code** [comment]
Nein, ich meinte das schon als Unterpaket von modules. Das Spielemodul
ist noch nicht mal halbfertig und schon jetzt viel zu lang. Alles über
100 Zeilen verdient eine eigene Klasse :wink:

Dadurch dass der Module-Loader nach dem Interface schaut wird dann auch
die richtige Hauptklasse geladen. Davon abgesehen finde ich ein package
gerechtfertigt, weil die Innereien den Rest des Programms nichts angehen
- es handelt sich _nicht_ um Helper-Methoden. Hat einfach was mit
  Organisation und Ordnung zu tun.

**Comment by mdoerfler** [comment]
Zitat aus dem Architekturdokument:
"Die eigentliche Analyse der Daten geschieht in unabhängigen Klassen, welche alle das In-
terface Analyzable implementieren und in einem gemeinsamen Package liegen."

Behaupten wir nicht hiermit, dass alles, was Analyse ist in einer Klasse des Interfaces Analyzable ist? :D 

Ich weiß nicht, ob das so ein bisschen gegen den Anfang von wegen ein Modul = eine Klasse verstößt...

**Comment by n2code** [comment]
Spätestens mit dem neuen Module Loader ist das ja auch kein Problem mehr...
Ich frage mich sowieso, ob man nicht noch an anderen Stellen unterteilen könnte, z.B. die GuiKlassen in einem Package zusammenfassen...
