### ISSUE TITLE
Rückgabewert des FileSearchers

### ISSUE THREAD

**Issue by momoXD007** [BigDaddy-Germany/WHOAMI#4]
Muss ich in den Modulen damit rechnen dass in der Methode "setFileInputs" als Wert "null" übergeben wird?

**Comment by mdoerfler** [comment]
Klares ja an dieser Stelle. Alleine schon für den Fall, dass keine entsprechenden Dateien gefunden wurden.

**Comment by momoXD007** [comment]
ok Anschlussfrage: dürfen die Module dann trotzdem ne Exception werfen, oder müssen die selber "damit klar kommen"?

**Comment by mdoerfler** [comment]
Ach eigentlich egal, ich werd dafür sorgen, dass die kein null bekommen sollten

**Comment by n2code** [comment]
Also bei keinem Fund eine leere `List<File>`?

**Comment by mdoerfler** [comment]
Exakt
