### ISSUE TITLE
ModuleLoader und JARs

### ISSUE THREAD

**Issue by n2code** [BigDaddy-Germany/WHOAMI#40]
- [x] ModuleLoader anpassen
- [x] JAR lauffähig machen
- [x] JavaFX bedenken

Wir müssen unbedingt ein Auge auf unser Deployment haben, schließlich wird alles früher oder später in eine JAR gepackt. Läuft soweit auch (unter _Project structure -> Artifacts_), aber der ModuleLoader kommt natürlich durcheinander, wenn man auf einmal nicht mehr mit `.class` Dateien ankommt...
Mögliches Stichwort: `getResources()` ?

Wichtiges Thema, schließlich sollen wir das Produkt auch liefern... :wink: 

PS: Mention @mdoerfler wegen dem Thema Module

**Comment by marvinklose** [comment]
JavaFX erbt nur von Klassen hat auf den Export glaube kaum Auswirkungen, außer das es eine .fxml für das Layout der GUIs gibt :+1:

**Comment by n2code** [comment]
okay, dann wäre der Punkt schonmal erledigt

**Comment by n2code** [comment]
alles andere nach der Umstellung eigentlich auch, momentan ist die Maven-generierte jar vollkommen lauffähig :+1:
