### ISSUE TITLE
Modultitel zurückgeben

### ISSUE THREAD

**Issue by mdoerfler** [BigDaddy-Germany/WHOAMI#44]
@momoXD007 @n2code @marvinklose @IngMiad 

Jedes Representable (also auch GlobalData) sollte nun zwei Titel zurückgeben:

`String getReportTitle()` gibt den Titel zurück, welcher im Report verwendet werden soll

`String getCsvPrefix()` gibt den Spaltenprefix zurück, welcher vor die Spalten der CSV-Datei gestellt werden soll.

Folgendes gilt es zu beachten:

ReportTitle nicht zu lang wählen, sodass es nix "zerschießt"

csvPrefix sollte keine Leerzeichen oder Sonderzeichen beinhalten. Der Prefix wird vom Spaltennamen durch einen Unterstrich getrennt.

Sollte eine der Methoden null zurückgeben (wie es aktuell im Master der Fall ist), wird später stattdessen der Klassenname des Modules genutzt.

**Comment by n2code** [comment]
Schreit das nicht so langsam nach
ModuleInfo getModuleInfo();
? Also einer Klasse? Wer weiß was für allgemeine Daten bald noch praktisch werden...

**Comment by mdoerfler** [comment]
Das kannst du ja intern so ablegen, halte ich aber für unpraktisch, falls diese Klasse dann auch den HTML-Content usw zurückgibt, weil ich brauche ja zb. für den Report nur die Report Infos und für die CSV die anderen

Wobei... Eigentlich ises mir egal :D
