### ISSUE TITLE
Firefox SQL-Statements erstellen

### ISSUE THREAD

**Issue by momoXD007** [BigDaddy-Germany/WHOAMI#45]
Es muss ein SQL Statement ertsellt werden welches die Daten möglichst weit vorselektiert vor Allem muss das Statement darauf Rücksicht nehemen dass man ein und dasselbe Feld unterschiedlich schreiben kann bsp.: "email","Email","E-Mail","E-Mailadresse","Email-Adresse","Mailadresse","Mailadresse"...

**Comment by momoXD007** [comment]
Für die Email-Adresse wird es vermutlich :"SELECT value,timesUsed,firstUsed,lastUsed FROM moz_formhistory where LOWER(fieldname) LIKE '%mail%' ORDER BY timesUsed DESC"

**Comment by momoXD007** [comment]
weiter verbessertes Statement:
SELECT value,SUM(timesUsed),firstUsed,lastUsed FROM moz_formhistory WHERE LOWER(fieldname) LIKE '%mail%' AND value LIKE '%@%' GROUP BY value ORDER BY SUM(timesUsed) DESC

Für den Ort sieht das Ganze dann so aus:
SELECT value,SUM(timesUsed),firstUsed,lastUsed FROM moz_formhistory WHERE LOWER(fieldname) LIKE '%ort%' OR LOWER(fieldname) LIKE '%city%' GROUP BY value ORDER BY SUM(timesUsed) DESC

**Comment by marvinklose** [comment]
Email (sind nicht case-sensitiv) :
SELECT LOWER(value) email,SUM(timesUsed) useCount,datetime(firstUsed/1000000,'unixepoch') erstmals ,datetime(lastUsed/1000000,'unixepoch') letztmals FROM moz_formhistory WHERE LOWER(fieldname) LIKE '%mail%' OR value LIKE '%@%' GROUP BY email ORDER BY useCount DESC

**Comment by momoXD007** [comment]
Danke für deine Hinweise. Allerdings ergibt sich daraus die Erkenntniss das die Daten in firstUsed und lastUsed anscheinend entweder falsch selektiert werden oder einfach schlecht in FF verwaltet sind. Weil firstUsed und lastUsed aktuell meist identisch sind was bei über 800 Benutzungen nicht richtig sein kann.

Also sie sind aktuell nicht brauchbar (siehe auch Screenshot unten).
![screen shot 2014-10-27 at 07 24 32](https://cloud.githubusercontent.com/assets/7457504/4786911/fa756644-5da1-11e4-9a43-18752354e4f4.png)

**Comment by marvinklose** [comment]
@momoXD007 in Chrome heißt die sqlite Datenbank "Web Data"
