### ISSUE TITLE
lastTimeUsed  und firstTimeUsed zu sinnvolen Datumsangaben umwandeln

### ISSUE THREAD

**Issue by momoXD007** [BigDaddy-Germany/WHOAMI#47]
Die Daten die da in der SQlite -DB sind scheinen sowas wie das zu sein was einem in java System.currentTimeMillis() ausgibt, das versteht ja kein normaler Mensch und von dahher wäre es schön das in eine verständliche Angabe umzuwandeln die auch jeder versteht.

**Comment by marvinklose** [comment]
@momoXD007 Die Funktion, die du schon im SQL einbauen kannst sieht so aus:
datetime(visit_date/1000000,'unixepoch') 
1403105982417000 --> 2014-06-18 15:39:42

**Comment by momoXD007** [comment]
die Informationen in der DB haben sich an dieser Stelle als nicht nützlich herausgestellt, und daher werden diese TimeStamps nicht genutzt
