### ISSUE TITLE
Korrektes XHTML verwenden

### ISSUE THREAD

**Issue by mdoerfler** [BigDaddy-Germany/WHOAMI#48]
Bitte prüft all eure HTML-Ausgaben ab jetzt auf Korrektheit bezüglich XHTML. Sonst wirft der Reportcreator aufgrund der HTML2PDF mit Exceptions um sich, bzw kann einfach keine PDF erstellen.

Mein Fehler war zum Beispiel, dass ich `<br>` genutzt habe und nicht `<br />`

Er hat dann festgestellt, dass das Closing Tag fehlt... 

@n2code @marvinklose @momoXD007 @IngMiad

**Comment by momoXD007** [comment]
Gibt's nen einfachen Weg das zu überprüfen zum Beispiel über den FF irgendwie? Also ich hab mein HTML einfach überprüft indem ich es als .html gespeichert hab und dann geguckt ob der FF damit klar kommt. Aber der ist ja nicht soooo streng, also gäbe es da einen ähnlich einfachen Weg das Ganze zu überprüfen?

**Comment by mdoerfler** [comment]
Master mergen (dass du den ReportCreator auch hast) und dann einfach sehen, obs ne Exception gibt :D
