### ISSUE TITLE
Abstimmung: Welche Scores und persönliche Daten?

### ISSUE THREAD

**Issue by mdoerfler** [BigDaddy-Germany/WHOAMI#49]
Langsam sollten wir uns einigen, welche Scores es geben soll und welche persönlichen Daten an die GlobalData weiter gereicht werden sollen.
Sonst kann man mit der GlobalData keinen wirklich brauchbaren HTML-Code erzeugen.

Meine Vorschläge bisher:

Scores:

Nerd, BWL, Faul

Daten:

Vorname, Nachname, Straße, PLZ, Ort, Telefonnummer(n)

**Comment by n2code** [comment]
Liegt nicht der Reiz darin, dass die GlobalData gar nicht vorher wissen muss, was sie geliefert bekommt? Man muss sich doch lediglich absprechen, wenn zwei Module zum gleichen Score beitragen, damit sie diesen dann auch gleich nennen...?

PS: Falls so ein Issue wichtiger ist bitte @mentions hinzfügen, habe das hier beispielsweise nur zufällig gesehen, ansonsten gehe ich nur nach meinen Notifications :wink:

**Comment by mdoerfler** [comment]
Ja das Modul an sich arbeitet auch und zwar ohne, dass die Scores vorher fest gelegt sind.

Ich war nur am überlegen, ob wir dafür sorgen sollen, dass die CSV-Spalten immer gleich aussehen, also auch die restlichen Module zur Not "Lieblingsessen" - "Keine Angabe" ausgeben, als eine Spalte weniger. Sonst ändert sich das Aussehen der CSV jedes mal und dadurch können die Daten nicht angehängt werden, sondern es wird jedes mal eine neue CSV erstellt. 

Oder sollen wir das mal ganz im Sinne des Architekturdokuments übersehen? ;D

Meinungen @n2code @momoXD007 @marvinklose @IngMiad ?

**Comment by momoXD007** [comment]
Muss meiner Meinung nach nicht. Erstmal die Sachen aus'em Pflichtenheft abarbeiten.=

**Comment by mdoerfler** [comment]
Sinnvolle Einschätzung. In diesem Sinne: Closed.
