### ISSUE TITLE
gefundene Files sinnvoll analysieren

### ISSUE THREAD

**Issue by momoXD007** [BigDaddy-Germany/WHOAMI#5]
Aktuell wird lediglich bewertet wie viele Rezepte gefunden werden und welches zuletzt geändert wurde. 
Dieser grobe "Algorithmus" wird noch dahingend verfeienert dass bewertet wird was für Rezepte gefunden werden evtl. auch die Dateigröße(große Datei--> langes Rezept-->kompliziertes Rezept-->Meisterkoch)

**Comment by n2code** [comment]
Idee: Dateigröße in Abhängigkeit vom Format einschätzen, z.B. "bei .txt zählt jedes Kilobyte, bei .docx zählt jedes KB über 20 vierfach (weil komprimiert), davor gar nichts (weil overhead)"

oder die ultimative Variante: Word files korrekt auswerten durch entpacken (sind eigentlich ZIPs mit z.B. style.xml, content.xml, ...)

**Comment by momoXD007** [comment]
meine vom obigen Kommentar vollkommen unabhängige Recherche hat ergeben das es wahrscheinlich auf ersteres hinauslaufen wird.
Inhalt sinnvoll parsen egal ob bei word oder txt scheint erstmal schwierig und ich weiß auch nicht ob man da an viele (erkenntnisliefernde) neue Informationen kommt.
