### ISSUE TITLE
HTML-Ausgabe der GlobalData anpassen

### ISSUE THREAD

**Issue by mdoerfler** [BigDaddy-Germany/WHOAMI#51]
Die HTML-Ausgabe der GlobalData ist momentan nur funktional gehalten, da ich mich auf die Logik dahinter konzentriert habe. 
Ich habe dafür eine Branch `globaldata` erstellt, falls das jemand übernehmen kann.

**Comment by marvinklose** [comment]
Hab in der Dropbox mal Beispiel Template angelegt

**Comment by mdoerfler** [comment]
Find ich richtig geil, was du da erstellt hast :+1: 
Das werd ich mir definitiv mal krallen und einbinden :)

**Comment by mdoerfler** [comment]
Implementiert und eingebaut.
