### ISSUE TITLE
Lizenz-Check

### ISSUE THREAD

**Issue by n2code** [BigDaddy-Germany/WHOAMI#52]
Lizenzen externer Komponenten checken sobald man externe Komponenten verwendet.
:information_source:  Dieser Reminder kann zu Projektende bei Erfüllung geschlossen werden. :information_source: 

@mdoerfler ist mir gerade bei deinem itext-PDF-Ersteller aufgefallen, bitte prüfe mal inwiefern uns die AGPL einschränkt oder was sie fordert

**Comment by mdoerfler** [comment]
Laut Phillip ist alles aus dem Central Repo unter Apache bzw. MIT also "mach damit was du willst"

**Comment by n2code** [comment]
Nur interessantere Kandidaten:
- [x] au.com.bytecode opencsv
- [x] org.xerial sqlite-jdbc
- [x] net.sf.javamusictag jid3lib
- [x] com.google.code.gson gson
- [x] jtidy jtidy
- [x] org.antlr antlr4
- [x] org.apache.commons commons-lang3
- [x] commons-io commons-io
- [x] org.reflections reflections
