### ISSUE TITLE
Korrektes SQLite Handling

### ISSUE THREAD

**Issue by mdoerfler** [BigDaddy-Germany/WHOAMI#53]
Zumindest bei der SAP Version des FireFox, wirft das Top5 Modul eine Exception alá `java.sql.SQLException: [SQLITE_CANTOPEN]  Unable to open the database file (unable to open database file)`

Michael und ich haben uns das gerade mal angesehen und wir gehen davon aus, dass es daran liegt, dass ich drei Places.sqlite auf dem Rechner habe - warum auch immer. Wahrscheinlich liegt das auch irgendwie mit daran, dass ich eine etwas "verkorkste" Version von SAP drauf habe. 

Du müsstest dafür sorgen, dass nicht funktionsfähige SQLite DBs weg geschmissen werden.

**Comment by marvinklose** [comment]
@mdoerfler Immernoch? Bzw. wenn ja bitte mit Zeilenangabe :+1:
