### ISSUE TITLE
Database SQLite Deadlock

### ISSUE THREAD

**Issue by marvinklose** [BigDaddy-Germany/WHOAMI#57]
Aufgrund von Threads kommen wir in die Situation, dass 2 Module gleichzeit eine Verbindung zur Datenbank wollen. Und dann gibts eine SQL Database locked Exception.

**Comment by marvinklose** [comment]
@IngMiad Bekommst du noch eine Databaselock Exception? Bzw. ist das Resultat das erwartete?

**Comment by IngMiad** [comment]
Nope, ich bekomme keine Databaselock Exception nicht mehr

**Comment by n2code** [comment]
ist das codeseitig gelöst? gerade bei unserer Parallelisierung könnte es ja sonst sein, dass es mal _zufällig_ geht und dann wieder _zufällig nicht_...

**Comment by IngMiad** [comment]
Nein bei mir geht es nicht. Ich kriege immer eine Nullpointer Exception vom Top5-Modul und das Essenmodul kriegt einfach keine  Ergebnisse, obwohl ich extra auf ganz vielen Chefkochseiten war.
Ich greife zusätzlich ja auch noch darauf zu (auch wenn irgendwas beim SQL-statement noch nicht passt)...?
