### ISSUE TITLE
Javadoc Kommentare nutzen

### ISSUE THREAD

**Issue by mdoerfler** [BigDaddy-Germany/WHOAMI#6]
@n2code @marvinklose @IngMiad @momoXD007 @mdoerfler

Minimum: Beschreibung einer Methode, deren Parameter und Return value

**Comment by n2code** [comment]
Exceptions ebenfalls. All dies zum Nachlesen im Architekturdokument, Abschnitt 6.4

**Comment by n2code** [comment]
wir haben einwandfrei unseren Code kommentiert :wink:
