### ISSUE TITLE
Studiengang anhand Dropbox herausfinden

### ISSUE THREAD

**Issue by n2code** [BigDaddy-Germany/WHOAMI#60]
- [x] `.dropbox`-Datei finden
- [x] Ordner darüber identifizieren
- [x] Vielleicht auch unabhängig von Dropbox suchen?
- [x] Liste erstellen un in JSON speichern: Studiengang im Klartext, als Regex und ein Kommentar dazu
- [ ] für jeden Fund: Ergebniswert der GlobalData vorschlagen

Dies ist ein beispielhafter Plan. Wer sich verpflichtet fühlt, bitte issue zuweisen und implementieren. Same procedure as every day :smile:

**Comment by marvinklose** [comment]
Letzte Verworfen
