### ISSUE TITLE
Spieleliste erstellen

### ISSUE THREAD

**Issue by n2code** [BigDaddy-Germany/WHOAMI#61]
Einträge: Spielename, Exe, Genre (auf eine Auswahl festlegen, metacritics Kategorien scheinen ganz brauchbar, siehe wiki)

Format zunächst egal, z.B. CSV in der Dropbox, später wird das auf JSON gemünzt

**Comment by marvinklose** [comment]
Hab noch 2-3 Einträge in der Dropbox ergänzt :+1:

**Comment by n2code** [comment]
Übertragung in JSON in Arbeit...

**Comment by n2code** [comment]
erledigt in 36a576846a86915f020257cbafcfb0512d0dddbb
