### ISSUE TITLE
Umgang mit mehr als 2 history-DBs verbessern

### ISSUE THREAD

**Issue by momoXD007** [BigDaddy-Germany/WHOAMI#63]
Falls man aktuell mehrere Installtionen von FF hat nimmt bzw. analysiert halt die Historty die er zuerst findet und ignoriert die Andere.

Wünschenswert wäre ein aufaddieren der Ergebnisse...

**Comment by marvinklose** [comment]
@momoXD007 denk an den Output  aus  #83

**Comment by marvinklose** [comment]
Michael den Rest + finaler Test

**Comment by momoXD007** [comment]
bin dran
