### ISSUE TITLE
Statistik aus Ergebnissen erstellen

### ISSUE THREAD

**Issue by mdoerfler** [BigDaddy-Germany/WHOAMI#68]

**Comment by marvinklose** [comment]
@mdoerfler Textform, wenn ja, soll ich mir was ausdenken?

**Comment by mdoerfler** [comment]
Liebend gerne, im Texte schreiben bin ich echt schlecht :DIch wollte die Anzahl der verschiedenen Programmiersprachen, die die am häufigsten verwendet wurde und wie gut oder schlecht der Syntax zu den Sprachen C und Java ist berechnen.

**Comment by marvinklose** [comment]
HTML für die reine Statistik der gefunden Quelltexte steht

**Comment by marvinklose** [comment]
@mdoerfler bei Gelegenheit, das Template mit deinen Werten füttern, du steckst in deinen Strukturen besser drin behaupte ich :smile:

**Comment by mdoerfler** [comment]
Wird gemacht ;)
