### ISSUE TITLE
Git: Projektdateien im Repo

### ISSUE THREAD

**Issue by n2code** [BigDaddy-Germany/WHOAMI#70]
In 48a6cdfc0f6f95a364fa57fd022b9e08fd835591 sind glaube ich ein paar Projektdateien ins Repo gerutscht, bitte prüfen und ggf korrigieren 
@mdoerfler du kennst dich damit aus, daher die Zuweisung

**Comment by mdoerfler** [comment]
Stimmt. Problem: wenn wir die jetzt löschen, werden die wieder bei jedem gelöscht. @IngMiad wir werden uns nachher am bestem mal hinsetzen, den commit reverten und neu mergend, dann hat keier Poblme mit seinen lokalen Daten.
