### ISSUE TITLE
Bugreport "Musikmodul: Errorhandling"

### ISSUE THREAD

**Issue by n2code** [BigDaddy-Germany/WHOAMI#71]
Der Log liegt auf Fehler reduziert in der Dropbox:
`/Wir als Lieferant/Errorlogs`

Bitte ein bisschen robusteres Errorhandling - und sei es nur durch geschicktes Pokemon Exception Handling an der ein oder anderen Stelle :wink:

**Comment by IngMiad** [comment]
Sieht der Log immer noch so aus?

**Comment by n2code** [comment]
stimmt, war heute Mittag nicht mehr so... falls doch wird das hier einfach reopened :wink:
