### ISSUE TITLE
ProposeData nutzen

### ISSUE THREAD

**Issue by mdoerfler** [BigDaddy-Germany/WHOAMI#75]
`GlobalData.getInstance().changeScore("Name des Benutzers: " + username, 0);` sollte nicht so genutzt werden. Die Funktion ist nur für Scores (Nerdscore usw) zu verwenden.

Jeder Fund von persönlichen Daten sollte abgefeuert werden. Auch wenn das selbe mehrmals gefunden wurde (oder genau dann), dass die Auswertung besser erfolgen kann.

**Comment by IngMiad** [comment]
Okay. Hab ich angepasst
