### ISSUE TITLE
Implementierung SQL Musik

### ISSUE THREAD

**Issue by marvinklose** [BigDaddy-Germany/WHOAMI#76]
- [ ] DataSourceManager verwenden statt selbst JDBC laden
- [ ] DataSourceManager mit Path füttern, dann Statement, dann Resultset verarbeiten
- [ ] Chrome nutzt Tabelle urls, Firefox Tabelle moz_places

@IngMiad

**Comment by n2code** [comment]
schreit das nicht schon fast nach einer statischen `searchHistory()`? @marvinklose 
Auch das Bonus-Modul "Letze Mail" wird das benötigen...

**Comment by marvinklose** [comment]
Jaein, der DataSourceManager implementiert kein unserer Interfaces und bekommt demnach kein FileInput
