### ISSUE TITLE
Musik Mapping in JSON

### ISSUE THREAD

**Issue by marvinklose** [BigDaddy-Germany/WHOAMI#77]
Eventuell, als enhancement, wenn sonst funktioniert ok

**Comment by n2code** [comment]
bitte stark darum, könnte sonst negativ auffallen

**Comment by IngMiad** [comment]
Was genau soll ich tun?

**Comment by IngMiad** [comment]
Das sagt mir nämlich garnichts :-D

*Ich markier euch jetzt mal wieder alle, als reminder:
@marvinklose @n2code @momoXD007 @mdoerfler

**Comment by n2code** [comment]
die Liste der ID3 Tags sollte in JSON ausgelagert werden, zusammen mit deren Kommentar (ggf. über ID verknüpfen damit wir keine redundanten Daten haben)

**Comment by IngMiad** [comment]
Boar ich hab gar keine Ahnung von JSON. Ich hab weder die Syntax noch den Sinn kapiert. Das dauert Ewigkeiten bis ich da durchsteige. Hab vor ein paar Tagen meine Monsterklasse in ein Package mit kleineren Unterklassen gepackt. Reicht das nicht...?

**Comment by n2code** [comment]
aus Zeitnot verworfen
