### ISSUE TITLE
Musik findet alle möglichen Resourcen von Steam Servern

### ISSUE THREAD

**Issue by marvinklose** [BigDaddy-Germany/WHOAMI#78]
Beispiel
Genre: [Vocal, Vocal, , , (12), , , , , , , (12), , , , , , , , , , , , , , , , , , , , , , , , (12), , , , , , , , , (12), , , Andere, , , , , , , Andere, , Andere, , , , Andere, Andere, , , , , , Other, , Other, Other, Other, Other, , , Other, Other, , Blues, , , , Other, (12), , Blues, Other, Other, (12), , , , (12), (12), (12), (

**Comment by n2code** [comment]
Ich fürchte es wird schwer, etwas dagegen zu machen...
Sollten Spiele MP3s mitliefern hat man keine Chance, es sei denn man schließt das Genre "Other" komplett aus von wegen "unaussagekräftig"...

**Comment by IngMiad** [comment]
Okay, bei der Liste werden vor der Analyse noch leere Einträge gelöscht und "(12)" ist der Byte-Wert zu Other. Der wird wegen den Klammern fehlerhaft als String gespeichert, aber am Ende umgewandelt in Other. Das sollte ich früher machen, sonst wird das ja nicht mitgewertet, kümmer ich mich noch drum. 
Ansonsten zählt "Other" aber als offizielles ID3Tag...

**Comment by IngMiad** [comment]
Okay es tauchen jetzt in der Liste keine "(NUMBER)", mehr auf. 

Was soll ich jetzt mit "Other" machen? Rausnehmen? Andere Ideen?
Oder wenn das immer von Spielen kommt, vllt sowas ausgeben wie "Du hast anscheinend mehr MP3-Files in deiner Spielebibliothek als sonst auf dem PC. Das Genre dieser Dateien wird als "Other/Andere" betitelt.

**Comment by n2code** [comment]
Das Problem ist, dass du ja dann wissen müsstest wo Spiele liegen, diese separat behandlen usw...
Ich persönlich würde _Other_ komplett rausnehmen, denn entweder wollen wir es nicht oder es hilft uns sowieso nicht bei einer Aussage... Damit würde man zwei Fliegen mit einer Klappe schlagen.
_Other_ kann ja auch soviel heißen wie "ich bin zu faul mir ein passendes Genre aus der offiziellen Liste zu suchen"

**Comment by marvinklose** [comment]
Oder wo Path.contains("game") || Path.contains("steam") --> ignore

**Comment by n2code** [comment]
das gilt ja für alle Spiele, die können ja sonstwo liegen...

**Comment by IngMiad** [comment]
Okay sollte "Other" das Genre mit den meisten Treffern sein, wird das zweithöchste genommen.
Bug fixed?

**Comment by n2code** [comment]
Findet ihr, Nicht-ID3-Genres sollten überhaupt gezählt werden?

**Comment by marvinklose** [comment]
Nicht bekannte ID3 Genres sollten finde ich geblacklisted sein!

**Comment by IngMiad** [comment]
1. Was meinst du mit nicht-ID3Genre?
2. Wieso soll man nicht einfach anzeigen, wenn jemand meinetwegen Jpop hört? Ich finds cool.

**Comment by marvinklose** [comment]
Ja so Eigenkreationen sind okay aber nicht irgendwie Steam Others :laughing:

**Comment by IngMiad** [comment]
Others ist ignored. Es gibt jetzt die alle ohne Other (http://de.wikipedia.org/wiki/Liste_der_ID3v1-Genres)

**Comment by marvinklose** [comment]
:clap:
