### ISSUE TITLE
Programmierstatistik

### ISSUE THREAD

**Issue by n2code** [BigDaddy-Germany/WHOAMI#81]
Über die Syntaxprüfung hinaus Statistiken zu Quelltexten erstellen

**Comment by marvinklose** [comment]
@mdoerfler Einfachste Lösung wäre bei dir einfach nach weiteren Endungen zu suchen und dann aber nur was auf .c oder .java endet zu parsen.

**Comment by n2code** [comment]
genau, das war impliziert :+1:
