### ISSUE TITLE
Text wird abgeschnitten anstatt umgebrochen

### ISSUE THREAD

**Issue by n2code** [BigDaddy-Germany/WHOAMI#82]
Wenn als Fließtext ausgegeben, sollte das eigentlich automatisch umbrechen...

**Comment by marvinklose** [comment]
Vermutung von Marco ganze steht in Table Tag

**Comment by IngMiad** [comment]
Okay ich habe jetzt den Fließtext bzw. das Fazit aus der Tabelle genommen

**Comment by mdoerfler** [comment]
Alles was außerhalb einer Tabelle steht wird automatisch umgebrochen, wie ein Test mit dem altbekannten Lorem Ipsum bewiesen hat.
Allerdings wird das ganze wohl kein Problem mehr sein, wenn wir das auf einen anderen HTML2PDF Dienst umstellen.
