### ISSUE TITLE
Report-Engine (HTML->PDF)

### ISSUE THREAD

**Issue by n2code** [BigDaddy-Germany/WHOAMI#84]
Der iText-Support ist mangelhaft, als alternative Lösungen sind zu validieren:
https://github.com/flyingsaucerproject/flyingsaucer
(weil er einen besseren CSS-renderer mitbringt - wie gut muss ausprobiert werden)

Oder die sichere und einfachste Variante:
http://wkhtmltopdf.org/
Das könnte in die JAR eingebunden und zur Laufzeit temporär entpackt (http://stackoverflow.com/a/463979) und verwendet werden.

**Comment by n2code** [comment]
kurze Tests haben ergeben: Der Weg des geringsten Aufwands und Widerstands (wkhtmltopdf) lässt die JAR nicht explodieren wie befürchtet, weil sich die EXE super packen lässt :wink:

**Comment by marvinklose** [comment]
Also fließt die Exe in die Jar?

**Comment by n2code** [comment]
Ich übernehme mal die Integration der `wkhtmltopdf`, denn das ist aktuell die wirtschaftlichste Lösung mit dem besten Kosten-Nutzen-Verhältnis

**Comment by n2code** [comment]
erledigt mit 23ff03f1223459e8ec33a4955212f3a19d2ddd41, Rückführung in den master folgt bald

**Comment by n2code** [comment]
Umstellung erfolgreich abgeschlossen :+1:
