### ISSUE TITLE
StackOverflow ?

### ISSUE THREAD

**Issue by marvinklose** [BigDaddy-Germany/WHOAMI#85]
Ich hab mal mit GUI Ausgabe alles laufen lassen und mal die den Taskmanager gescreenshotet
![screenshot 2014-11-01 10 54 13](https://cloud.githubusercontent.com/assets/7312459/4871345/6fca6588-61ae-11e4-8470-633abd04fd0e.png)

Probleme
A) Der FileSearcher findet soviel, dass er irgendwann nicht mehr weiß wohin mit seinen Paths :-1:  
B) Irgendein Modul kommt einfach nicht zum Punkt  :fu:

**Comment by marvinklose** [comment]
Habe 2 Risiken identifizieren können 
1. @mdoerfler alle Module laufen durch bis auf das Codingmodul, das anscheinend auch alles der Java Installation mit parsen will, und das Backtracking von ANTLR erzeugt dann wie auf Android Ruckzuck eine mega Auslastung vom RAM.
2. @momoXD007 Food ist noch nicht fertig

**Comment by momoXD007** [comment]
Was fehlt denn noch?

**Comment by marvinklose** [comment]
Kann sein das es ja mit dem nächsten weggeht

**Comment by mdoerfler** [comment]
Wurde behoben. ANTR frisst keine Ressourcen mehr.
