### ISSUE TITLE
Nur einzelne Java und C Dateien parsen?

### ISSUE THREAD

**Issue by mdoerfler** [BigDaddy-Germany/WHOAMI#86]
Da ANTLR (und auch alle anderen Parser) wohl wirklich seeehr lange brauchen, um eine hohe Anzahl an Java Dateien zu parsen (Alleine in meiner Dropbox ca 12.000 Funde) ist mir die Idee gekommen, die Statistik über Anzahl und Art der Dateien zwar auf alle Funde zu beziehen, aber das Parsen an sich nur auf eine bestimmte (pseudo-Zufalls-) Auswahl zu beziehen. So nach dem Motto ich parse zufällige 1000 Funde und werde dann sicherlich auf einen realistischen Schnitt deiner Syntaxfehler kommen. 

Meinungen dazu @n2code @marvinklose @momoXD007 @IngMiad ?

**Comment by IngMiad** [comment]
Ja halte ich für eine sehr gute Idee :+1:

**Comment by n2code** [comment]
Dafür :+1: 
aaaaber bitte offensichtlich Nicht-Selbstgeschriebenes (im Pfad "jdk"/"jre"/...) ausschließen :smile:

**Comment by marvinklose** [comment]
Schließe mich Niko an :+1:

**Comment by momoXD007** [comment]
Ich ebenso.
