### ISSUE TITLE
Dokumentation Berichtzusammenstellung

### ISSUE THREAD

**Issue by n2code** [BigDaddy-Germany/WHOAMI#89]
Wie arbeiten die Module und wie sind die Ergebnisse zu interpretieren (Aufschlüsselung)

**Comment by momoXD007** [comment]
hat schon wer angefangen? Also wird das in latex gemacht oder wie soll das laufen?

**Comment by n2code** [comment]
wäre für latex, im orga-repo

**Comment by momoXD007** [comment]
Habe begonnen Nikos Vorschlag eigenmächtig umzusetzen, also es gibt Arbeit im anderen Repo. Sprich jeder sollte nen kurzen Absatz schreiben am besten über die eigenen Module.

**Comment by momoXD007** [comment]
@n2code @IngMiad  @marvinklose @mdoerfler  viel Spaß beim Doku schreiben...

Aja wenn wer ne bessere Vorlage als meine noch ziemlich anpassungsbedürftige Praxisphasenbericht-Vorlage findet können wir auch die nehemen. Ich hab online allerdings nix brauchbares gefunden...

**Comment by n2code** [comment]
die Vorlage ist echt total egal, einfach Fließtext und gut ist...
wie wärs vielleicht mit eurer datenmethoden-Vorlage? Zweispaltig sieht sicher gut aus :+1: aber bitte serifenlose Schrift....

**Comment by n2code** [comment]
Design ist da, Inhalt ist da, alles ist da :smiley:
