### ISSUE TITLE
Time-Boxing in Modulen implementieren

### ISSUE THREAD

**Issue by mdoerfler** [BigDaddy-Germany/WHOAMI#9]
@n2code @marvinklose @momoXD007 @IngMiad 

Bei all euren Modulen darauf achten, dass ihr irgendwo die Möglichkeit habt, timeboxing zu betreiben. Ob wir die Zeit dann als final static in der whoami klasse ablegen oder so, sehen wir dann ja (wäre mein Vorschlag), aber es kann ja jeder schonmal die entsprechende Funktionalität einbauen.

**Comment by n2code** [comment]
Eine global erreichbare Methode à la `boolean isTimeUp()` wäre vielleicht sinnvoll, damit kann jedes Modul in jedem Schleifendurchgang fragen, ob es noch weitermachen darf...

Alternativ und komplexer: `int getTimeProgress` liefert Werte von 0-100 wieviel von der erlaubten Scanzeit schon verstrichen ist - 100 äquivalent zu **"die Zeit ist um sofort aufhören"**

**Comment by mdoerfler** [comment]
Gute Idee. Setze ich so um.

**Comment by momoXD007** [comment]
also die Module erfragen wie viel Zeit sie noch ham beim Whoami-Scanner? Dafür brauchen sie aber ne Referenz zu dieser Klasse oder die muss Singleton sein...

**Comment by mdoerfler** [comment]
Da main ja static ist, wird es auch ne static Methode dafür geben. Singleton ist also nicht nötig.

**Comment by mdoerfler** [comment]
Die Methode steht nun im Master zur Verfügung.

**Comment by marvinklose** [comment]
Wie wäre es mit !Thread.currentThread().isInterrupted() in den Runs der Module?
Dann könnte man global alle Threads nach 30 Minuten mit essenThread.interrupt() kontrolliert zu Ende bringen?!

**Comment by n2code** [comment]
Das erfüllt diese Methode auch, aber der Sinn ist, dass das Modul auch weiß, wie viel Zeit es noch hat. Frei nach dem Motto _"Was, schon die Hälfte der Zeit um? Dann mache ich jetzt lieber mit dem zweiten Schritt weiter und untersuche eben nicht **ALLE** Dateien..."_

**Comment by mdoerfler** [comment]
Methode ist nun kommentiert und nutzt die Millisekunden. Scheinbar war der thread auf Stackoverflow bullshit. Danke für den Hinweis Marv!

**Comment by n2code** [comment]
Was wurde eigentlich aus dem Vorschlag, dass sich 0-100 auf die Zeit bezieht, welche die Module haben?

**Comment by mdoerfler** [comment]
Wenns gebraucht wird, kann ich das umsetzen.

**Comment by n2code** [comment]
wenn ich nach der Hälfte der Zeit fortfahren wollte, was müsste ich dann als Vergleichswert nehmen? 88?

**Comment by mdoerfler** [comment]
Das hängt davon ab, wie viel Prozent dem Filesearcher zugeordnet werden und vor allem wie viel er tatsächlich gebraucht hat. Wenn du es benötigst ist es wohl sinnvoll, dass ich es noch umsetze.

**Comment by n2code** [comment]
okay, solange ich nur Timeboxing mit "Abbruch wenn >=99" verwende mach ich einfach so weiter und sobald ich das für ein anderes Modul benötige, melde ich mich :+1:

**Comment by mdoerfler** [comment]
Okay mach das

**Comment by mdoerfler** [comment]
In nächster Zeit kommt ein Update, welches die Module abschießt, wenn sie zu lange brauchen. Nachdem die Zeit um ist, werden den Modulen noch weitere 5 Sekunden gewährt. 

Für den Fall der Fälle könnt ihr eine InterruptedException abfangen, wenn ihr wollt. Solltet ihr euch an das Timeboxing halten, ist das allerdings nicht nötig.
