### ISSUE TITLE
Musik stirbt ab

### ISSUE THREAD

**Issue by marvinklose** [BigDaddy-Germany/WHOAMI#92]
![inga](https://cloud.githubusercontent.com/assets/7312459/4905209/d8abd090-644d-11e4-9220-3512fcc61457.PNG)

**Comment by marvinklose** [comment]
@IngMiad meine Vermutung nachm Debuggen ist das die F:\Musik\All\B\Benny Benassi Presents the Biz - No Matter What You Do (Caged B.mp3
bei sowas die ( nicht mögen ;)

**Comment by IngMiad** [comment]
Unsauber aber wirksam: unten an die Methode catch (Exception e) drangehangen

**Comment by mdoerfler** [comment]
Dann wird allerdings das entsprechende Lied ignoriert

Bekommt man das auch so hin, dass das Lied nicht ignoriert wird?

**Comment by IngMiad** [comment]
Der kann halt kein MP3-Objekt von der Datei machen. Kann gut sein, dass es am Namen liegt. 
Man könnte natürlich Dateien mit diesem Fehler umbenennen und ihnen nach der Analyse wieder ihren alten Namen zu geben.

**Comment by mdoerfler** [comment]
Schlechte Idee - Wenn dein Modul dann zwischenzeitlich abgeschossen wird, haben wir Dinge auf dem Computer verändert und das dürfen wir nicht.
Dann lieber eine Datei weniger nutzen, wenn es gar nicht geht. Aber vielleicht findet sich ja noch ein Weg, wie man auch solche Dateien analysieren kann.

**Comment by IngMiad** [comment]
Ich hab keine Idee dazu.
